import Foundation

/// Hand-written SAT Reading & Writing practice, modeled on the digital SAT question types.
enum SATReadingWriting {
    private static func b(_ topic: String, _ i: Int, _ prompt: String, _ answer: String, _ wrong: [String], _ why: String) -> Question {
        Question.make(topicID: topic, prompt: prompt, answer: answer, distractors: wrong, explanation: why, id: "\(topic)#\(i)")
    }

    static let topics: [(String, String, [Question])] = [
        ("sat.boundaries", "Boundaries: Punctuation", [
            b("sat.boundaries", 1, "The museum's newest exhibit features artifacts from three ancient ______ Egypt, Mesopotamia, and the Indus Valley.",
              "civilizations:", ["civilizations,", "civilizations;", "civilizations"],
              "A colon introduces a list that explains what came before it."),
            b("sat.boundaries", 2, "Marie Curie won two Nobel ______ she remains the only person honored in two different sciences.",
              "Prizes;", ["Prizes,", "Prizes", "Prizes and,"],
              "Two independent clauses need a semicolon (a comma alone creates a comma splice)."),
            b("sat.boundaries", 3, "The novel, which was published in ______ became an instant bestseller.",
              "1925,", ["1925", "1925;", "1925:"],
              "The nonessential clause opened with a comma must close with a comma."),
            b("sat.boundaries", 4, "Researchers studied the ______ tail feathers to understand how the birds attract mates.",
              "peacocks'", ["peacocks", "peacocks's", "peacock"],
              "Plural possessive (many peacocks) takes an apostrophe after the s."),
            b("sat.boundaries", 5, "Although the experiment ______ the team published its data anyway.",
              "failed,", ["failed;", "failed.", "failed:"],
              "A dependent clause (\"Although…\") joins the main clause with a comma."),
            b("sat.boundaries", 6, "The chef insisted on one rule above all ______ never serve a dish you would not eat yourself.",
              "others:", ["others,", "others", "others, and"],
              "A colon introduces an explanation or elaboration of \"one rule.\""),
            b("sat.boundaries", 7, "Octopuses are remarkably ______ they can solve puzzles and open jars.",
              "intelligent—", ["intelligent,", "intelligent", "intelligent and,"],
              "A dash (like a colon) can join a clause to one that explains it; a comma would be a splice."),
            b("sat.boundaries", 8, "The city's ______ built in 1890, still carries thousands of commuters each day.",
              "bridge,", ["bridge", "bridge;", "bridge:"],
              "A comma sets off the descriptive phrase \"built in 1890.\""),
        ]),
        ("sat.agreement", "Subject-Verb Agreement", [
            b("sat.agreement", 1, "The collection of rare coins ______ displayed in the east wing.",
              "is", ["are", "were", "have been"], "The subject is \"collection\" (singular), not \"coins.\""),
            b("sat.agreement", 2, "Neither the players nor the coach ______ happy with the referee's decision.",
              "was", ["were", "are", "have been"], "With neither/nor, the verb agrees with the nearer subject: \"coach.\""),
            b("sat.agreement", 3, "Each of the paintings ______ a hidden signature.",
              "contains", ["contain", "are containing", "have contained"], "\"Each\" is singular."),
            b("sat.agreement", 4, "The data from the recent surveys ______ that commuting times have increased.",
              "suggest", ["suggests", "is suggesting", "has suggested"],
              "On the SAT, \"data\" is treated as plural."),
            b("sat.agreement", 5, "Among the island's most famous attractions ______ a lighthouse built in 1802.",
              "is", ["are", "were", "have been"], "Inverted sentence: the subject \"a lighthouse\" follows the verb."),
            b("sat.agreement", 6, "The number of students applying to college ______ risen each year.",
              "has", ["have", "are", "were"], "\"The number\" is singular (\"a number\" would be plural)."),
        ]),
        ("sat.tense", "Verb Tense & Form", [
            b("sat.tense", 1, "By the time the rescue team arrived, the hikers ______ for two days.",
              "had been waiting", ["have been waiting", "are waiting", "will wait"], "Past perfect progressive for an action continuing up to a past moment."),
            b("sat.tense", 2, "In 1969, Neil Armstrong ______ onto the surface of the Moon.",
              "stepped", ["steps", "has stepped", "will step"], "Simple past for a completed event at a specific past time."),
            b("sat.tense", 3, "Scientists predict that sea levels ______ significantly by 2100.",
              "will rise", ["rose", "had risen", "have rose"], "Future tense for a prediction."),
            b("sat.tense", 4, "She has ______ three marathons this year.",
              "run", ["ran", "runned", "running"], "\"Has\" takes the past participle \"run.\""),
            b("sat.tense", 5, "When the bell rang, the students ______ their books and left.",
              "closed", ["close", "have closed", "are closing"], "Keep tense consistent with \"rang.\""),
        ]),
        ("sat.pronouns", "Pronouns & Modifiers", [
            b("sat.pronouns", 1, "The committee announced ______ decision after a long debate.",
              "its", ["their", "it's", "they're"], "\"Committee\" is a singular collective noun."),
            b("sat.pronouns", 2, "Between you and ______, the plan is flawed.",
              "me", ["I", "myself", "mine"], "Objects of a preposition use the objective case."),
            b("sat.pronouns", 3, "Walking through the forest, ______.",
              "we heard a woodpecker tapping", ["a woodpecker's tapping could be heard", "the tapping of a woodpecker was heard", "there was a woodpecker tapping"],
              "The modifier \"Walking through the forest\" must describe the subject that follows it: \"we.\""),
            b("sat.pronouns", 4, "The tourists and ______ guide boarded the bus.",
              "their", ["there", "they're", "its"], "Plural possessive pronoun."),
            b("sat.pronouns", 5, "Having finished the report, ______.",
              "Priya submitted it to her manager", ["the report was submitted by Priya", "it was submitted to the manager", "the manager received the report"],
              "The person who finished the report must come right after the comma."),
        ]),
        ("sat.transitions", "Transitions", [
            b("sat.transitions", 1, "The drug showed promise in early trials. ______, later studies revealed serious side effects.",
              "However", ["Similarly", "Therefore", "For example"], "Contrast between promise and side effects."),
            b("sat.transitions", 2, "Bees are vital to agriculture. ______, they pollinate roughly a third of the crops we eat.",
              "In fact", ["Nevertheless", "In contrast", "Meanwhile"], "The second sentence emphasizes and supports the first."),
            b("sat.transitions", 3, "The town's population doubled in a decade. ______, demand for housing soared.",
              "As a result", ["Nonetheless", "Likewise", "Instead"], "Cause and effect."),
            b("sat.transitions", 4, "Some critics dismissed the film as shallow. ______, audiences flocked to theaters to see it.",
              "Still", ["Thus", "Specifically", "Furthermore"], "Contrast: despite the criticism."),
            b("sat.transitions", 5, "The artist worked mainly in oils. ______, she experimented with watercolor late in life.",
              "Later", ["Consequently", "In other words", "Similarly"], "Time sequence shift."),
            b("sat.transitions", 6, "Frogs absorb water through their skin. ______, they are highly sensitive to pollutants.",
              "Consequently", ["However", "Previously", "By contrast"], "The permeable skin causes sensitivity."),
        ]),
        ("sat.wordsincontext", "Words in Context", [
            b("sat.wordsincontext", 1, "The senator's speech was so ______ that even her opponents admitted she had made a convincing case.",
              "compelling", ["tedious", "ambiguous", "trivial"], "Opponents conceding the case implies persuasive."),
            b("sat.wordsincontext", 2, "Though the scientist was usually ______, she spoke at length about her discovery.",
              "reticent", ["garrulous", "boisterous", "candid"], "\"Though\" signals contrast with speaking at length."),
            b("sat.wordsincontext", 3, "The fossil record for the species is ______: only a few fragments have ever been found.",
              "sparse", ["abundant", "pristine", "redundant"], "Only a few fragments means scarce."),
            b("sat.wordsincontext", 4, "The author's style is ______; she uses as few words as possible.",
              "terse", ["florid", "verbose", "ornate"], "Few words = terse."),
            b("sat.wordsincontext", 5, "The reforms were meant to ______ corruption, but they ended up making it worse.",
              "curb", ["foster", "exacerbate", "celebrate"], "\"But… worse\" contrasts with the intended effect: to restrain."),
            b("sat.wordsincontext", 6, "Her ______ approach to research—checking every source twice—earned her colleagues' respect.",
              "meticulous", ["careless", "haphazard", "cursory"], "Checking twice = extremely careful."),
            b("sat.wordsincontext", 7, "The evidence was ______, so the jury could not reach a clear verdict.",
              "equivocal", ["conclusive", "irrefutable", "definitive"], "Unclear evidence prevents a clear verdict."),
        ]),
        ("sat.evidence", "Central Ideas & Evidence", [
            b("sat.evidence", 1, "A study found that students who slept 8+ hours scored higher on memory tests than those who slept 5 hours. Which choice best states the main finding?",
              "More sleep was associated with better memory performance.", ["Memory tests cause students to sleep more.", "All students should sleep exactly 8 hours.", "Sleep has no effect on test scores."],
              "The finding is a correlation between sleep and scores; it doesn't prove causation in reverse or prescribe exact hours."),
            b("sat.evidence", 2, "A researcher claims urban gardens improve neighborhood well-being. Which finding would most directly support this claim?",
              "Residents near gardens reported lower stress levels than similar residents farther away.",
              ["Urban gardens require regular watering.", "Most urban gardens grow tomatoes.", "Gardens were first planted in cities centuries ago."],
              "Only this option measures well-being in relation to gardens."),
            b("sat.evidence", 3, "Text: \"Although the ruins had been studied for a century, new radar scans revealed an entire district no one had suspected.\" What is the main idea?",
              "New technology uncovered previously unknown parts of the ruins.", ["The ruins were studied for exactly 100 years.", "Radar is too inaccurate for archaeology.", "The district was built recently."],
              "The sentence emphasizes the new discovery made by radar."),
            b("sat.evidence", 4, "A student wants to emphasize a similarity between two poets. Which choice best accomplishes this goal?",
              "Like Dickinson, Whitman broke with traditional poetic forms.", ["Dickinson wrote in Massachusetts; Whitman lived in New York.", "Whitman published Leaves of Grass in 1855.", "Dickinson's poems were published after her death."],
              "Only this option states what the poets have in common."),
            b("sat.evidence", 5, "Which choice most logically completes the text? \"Crows that were shown a masked 'threatening' person scolded that mask for years afterward, and so did crows that never saw the original event. This suggests that crows ______\"",
              "can learn about threats from other crows.", ["cannot recognize human faces.", "forget threats quickly.", "are only afraid of masks."],
              "Crows that never saw the event still reacted, implying social learning."),
        ]),
    ]
}
