// Generated by tools/export-web-content.py from the iOS Swift content. Do not edit by hand.
window.PL_DATA = {
 "decks": [
  {
   "id": "sat.vocab.1",
   "name": "SAT Vocab I",
   "subject": "vocab",
   "forward": "What does “%@” mean?",
   "reverse": "Which word means: %@?",
   "pairs": [
    [
     "abate",
     "to become less intense"
    ],
    [
     "aberration",
     "a departure from what is normal"
    ],
    [
     "abstruse",
     "difficult to understand"
    ],
    [
     "acquiesce",
     "to accept reluctantly without protest"
    ],
    [
     "acrimonious",
     "angry and bitter"
    ],
    [
     "adroit",
     "skillful and clever"
    ],
    [
     "aesthetic",
     "concerned with beauty"
    ],
    [
     "alacrity",
     "brisk and cheerful readiness"
    ],
    [
     "ambivalent",
     "having mixed feelings"
    ],
    [
     "ameliorate",
     "to make something better"
    ],
    [
     "anachronistic",
     "out of its proper time period"
    ],
    [
     "anomaly",
     "something that deviates from the norm"
    ],
    [
     "antithesis",
     "the direct opposite"
    ],
    [
     "apathy",
     "lack of interest or concern"
    ],
    [
     "arbitrary",
     "based on random choice, not reason"
    ],
    [
     "arduous",
     "requiring great effort"
    ],
    [
     "articulate",
     "able to express ideas clearly"
    ],
    [
     "ascetic",
     "practicing severe self-discipline"
    ],
    [
     "assuage",
     "to make an unpleasant feeling less intense"
    ],
    [
     "audacious",
     "showing bold willingness to take risks"
    ]
   ]
  },
  {
   "id": "sat.vocab.2",
   "name": "SAT Vocab II",
   "subject": "vocab",
   "forward": "What does “%@” mean?",
   "reverse": "Which word means: %@?",
   "pairs": [
    [
     "austere",
     "severe or strict in manner; plain"
    ],
    [
     "banal",
     "lacking originality; boring"
    ],
    [
     "belligerent",
     "hostile and aggressive"
    ],
    [
     "benevolent",
     "well-meaning and kindly"
    ],
    [
     "bolster",
     "to support or strengthen"
    ],
    [
     "brevity",
     "concise use of words"
    ],
    [
     "cacophony",
     "a harsh mixture of sounds"
    ],
    [
     "candor",
     "the quality of being open and honest"
    ],
    [
     "capricious",
     "given to sudden changes of mood"
    ],
    [
     "catalyst",
     "something that causes change"
    ],
    [
     "circumspect",
     "wary and unwilling to take risks"
    ],
    [
     "coalesce",
     "to come together to form one whole"
    ],
    [
     "cogent",
     "clear, logical, and convincing"
    ],
    [
     "complacent",
     "smugly satisfied; unaware of danger"
    ],
    [
     "concede",
     "to admit something is true after first denying it"
    ],
    [
     "conciliatory",
     "intended to make peace"
    ],
    [
     "conundrum",
     "a confusing and difficult problem"
    ],
    [
     "corroborate",
     "to confirm or give support to"
    ],
    [
     "credulous",
     "too ready to believe things"
    ],
    [
     "culpable",
     "deserving blame"
    ]
   ]
  },
  {
   "id": "sat.vocab.3",
   "name": "SAT Vocab III",
   "subject": "vocab",
   "forward": "What does “%@” mean?",
   "reverse": "Which word means: %@?",
   "pairs": [
    [
     "dearth",
     "a scarcity or lack"
    ],
    [
     "deference",
     "humble submission and respect"
    ],
    [
     "delineate",
     "to describe or portray precisely"
    ],
    [
     "denigrate",
     "to criticize unfairly; disparage"
    ],
    [
     "diligent",
     "showing care and effort in work"
    ],
    [
     "discern",
     "to perceive or recognize"
    ],
    [
     "disparate",
     "essentially different in kind"
    ],
    [
     "dogmatic",
     "stating opinions as undeniably true"
    ],
    [
     "eclectic",
     "drawn from diverse sources"
    ],
    [
     "efficacy",
     "the ability to produce a desired result"
    ],
    [
     "elusive",
     "difficult to find or catch"
    ],
    [
     "empirical",
     "based on observation or experience"
    ],
    [
     "ephemeral",
     "lasting a very short time"
    ],
    [
     "equivocal",
     "open to more than one interpretation"
    ],
    [
     "erudite",
     "having great knowledge"
    ],
    [
     "exacerbate",
     "to make a problem worse"
    ],
    [
     "exemplary",
     "serving as a desirable model"
    ],
    [
     "extol",
     "to praise enthusiastically"
    ],
    [
     "fastidious",
     "very attentive to detail"
    ],
    [
     "fervent",
     "having intense feeling"
    ]
   ]
  },
  {
   "id": "sat.vocab.4",
   "name": "SAT Vocab IV",
   "subject": "vocab",
   "forward": "What does “%@” mean?",
   "reverse": "Which word means: %@?",
   "pairs": [
    [
     "frugal",
     "sparing or economical with money"
    ],
    [
     "garrulous",
     "excessively talkative"
    ],
    [
     "gregarious",
     "fond of company; sociable"
    ],
    [
     "hackneyed",
     "overused and unoriginal"
    ],
    [
     "hubris",
     "excessive pride or self-confidence"
    ],
    [
     "iconoclast",
     "a person who attacks cherished beliefs"
    ],
    [
     "impetuous",
     "acting quickly without thought"
    ],
    [
     "incisive",
     "intelligently analytical and clear"
    ],
    [
     "indifferent",
     "having no particular interest"
    ],
    [
     "innocuous",
     "not harmful or offensive"
    ],
    [
     "intrepid",
     "fearless; adventurous"
    ],
    [
     "laconic",
     "using very few words"
    ],
    [
     "lethargic",
     "sluggish and apathetic"
    ],
    [
     "lucid",
     "expressed clearly; easy to understand"
    ],
    [
     "magnanimous",
     "generous and forgiving"
    ],
    [
     "malleable",
     "easily influenced or shaped"
    ],
    [
     "meticulous",
     "showing great attention to detail"
    ],
    [
     "mitigate",
     "to make less severe"
    ],
    [
     "mundane",
     "lacking interest; ordinary"
    ],
    [
     "nefarious",
     "wicked or criminal"
    ]
   ]
  },
  {
   "id": "sat.vocab.5",
   "name": "SAT Vocab V",
   "subject": "vocab",
   "forward": "What does “%@” mean?",
   "reverse": "Which word means: %@?",
   "pairs": [
    [
     "novice",
     "a person new to an activity"
    ],
    [
     "obdurate",
     "stubbornly refusing to change"
    ],
    [
     "obsolete",
     "no longer produced or used"
    ],
    [
     "opulent",
     "ostentatiously rich and luxurious"
    ],
    [
     "paradigm",
     "a typical example or model"
    ],
    [
     "paucity",
     "the presence of something in small amounts"
    ],
    [
     "pragmatic",
     "dealing with things practically"
    ],
    [
     "precocious",
     "developed abilities at an early age"
    ],
    [
     "prolific",
     "producing much fruit or many works"
    ],
    [
     "prosaic",
     "lacking poetic beauty; dull"
    ],
    [
     "quandary",
     "a state of uncertainty over what to do"
    ],
    [
     "rancor",
     "bitterness or resentfulness"
    ],
    [
     "recalcitrant",
     "uncooperative toward authority"
    ],
    [
     "reticent",
     "not revealing one's thoughts readily"
    ],
    [
     "reverent",
     "feeling deep respect"
    ],
    [
     "sagacious",
     "having good judgment; wise"
    ],
    [
     "scrupulous",
     "diligent and extremely careful"
    ],
    [
     "soporific",
     "tending to induce sleep"
    ],
    [
     "spurious",
     "false or fake"
    ],
    [
     "stoic",
     "enduring pain without complaint"
    ]
   ]
  },
  {
   "id": "sat.vocab.6",
   "name": "SAT Vocab VI",
   "subject": "vocab",
   "forward": "What does “%@” mean?",
   "reverse": "Which word means: %@?",
   "pairs": [
    [
     "substantiate",
     "to provide evidence to support"
    ],
    [
     "superfluous",
     "unnecessary; more than enough"
    ],
    [
     "tenacious",
     "persistent; not giving up"
    ],
    [
     "tenuous",
     "very weak or slight"
    ],
    [
     "ubiquitous",
     "present everywhere"
    ],
    [
     "undermine",
     "to weaken gradually"
    ],
    [
     "vacillate",
     "to waver between opinions"
    ],
    [
     "venerate",
     "to regard with great respect"
    ],
    [
     "verbose",
     "using more words than needed"
    ],
    [
     "vindicate",
     "to clear of blame"
    ],
    [
     "volatile",
     "liable to change rapidly"
    ],
    [
     "zealous",
     "having great energy for a cause"
    ]
   ]
  },
  {
   "id": "vocab.roots.1",
   "name": "Greek & Latin Roots I",
   "subject": "vocab",
   "forward": "What does the root “%@” mean?",
   "reverse": "Which root means “%@”?",
   "pairs": [
    [
     "bene",
     "good, well"
    ],
    [
     "mal",
     "bad"
    ],
    [
     "chron",
     "time"
    ],
    [
     "graph",
     "write"
    ],
    [
     "phil",
     "love"
    ],
    [
     "phob",
     "fear"
    ],
    [
     "bio",
     "life"
    ],
    [
     "geo",
     "earth"
    ],
    [
     "hydr",
     "water"
    ],
    [
     "therm",
     "heat"
    ],
    [
     "tele",
     "far"
    ],
    [
     "micro",
     "small"
    ],
    [
     "port",
     "carry"
    ],
    [
     "dict",
     "say, speak"
    ],
    [
     "spect",
     "look, see"
    ],
    [
     "scrib",
     "write"
    ],
    [
     "rupt",
     "break"
    ],
    [
     "tract",
     "pull, drag"
    ],
    [
     "ject",
     "throw"
    ],
    [
     "vid",
     "see"
    ]
   ]
  },
  {
   "id": "vocab.roots.2",
   "name": "Greek & Latin Roots II",
   "subject": "vocab",
   "forward": "What does the root “%@” mean?",
   "reverse": "Which root means “%@”?",
   "pairs": [
    [
     "aud",
     "hear"
    ],
    [
     "cred",
     "believe"
    ],
    [
     "fid",
     "faith, trust"
    ],
    [
     "loqu",
     "speak, talk"
    ],
    [
     "omni",
     "all"
    ],
    [
     "pan",
     "all, every"
    ],
    [
     "anthrop",
     "human"
    ],
    [
     "path",
     "feeling, suffering"
    ],
    [
     "morph",
     "shape, form"
    ],
    [
     "ambi",
     "both"
    ]
   ]
  },
  {
   "id": "geo.cap.europe",
   "name": "Capitals: Europe",
   "subject": "geography",
   "forward": "What is the capital of %@?",
   "reverse": "%@ is the capital of…",
   "pairs": [
    [
     "France",
     "Paris"
    ],
    [
     "Germany",
     "Berlin"
    ],
    [
     "Italy",
     "Rome"
    ],
    [
     "Spain",
     "Madrid"
    ],
    [
     "Portugal",
     "Lisbon"
    ],
    [
     "Netherlands",
     "Amsterdam"
    ],
    [
     "Belgium",
     "Brussels"
    ],
    [
     "Switzerland",
     "Bern"
    ],
    [
     "Austria",
     "Vienna"
    ],
    [
     "Poland",
     "Warsaw"
    ],
    [
     "Czech Republic",
     "Prague"
    ],
    [
     "Hungary",
     "Budapest"
    ],
    [
     "Greece",
     "Athens"
    ],
    [
     "Sweden",
     "Stockholm"
    ],
    [
     "Norway",
     "Oslo"
    ],
    [
     "Denmark",
     "Copenhagen"
    ],
    [
     "Finland",
     "Helsinki"
    ],
    [
     "Ireland",
     "Dublin"
    ],
    [
     "United Kingdom",
     "London"
    ],
    [
     "Ukraine",
     "Kyiv"
    ],
    [
     "Romania",
     "Bucharest"
    ],
    [
     "Bulgaria",
     "Sofia"
    ],
    [
     "Croatia",
     "Zagreb"
    ],
    [
     "Serbia",
     "Belgrade"
    ],
    [
     "Iceland",
     "Reykjavík"
    ],
    [
     "Estonia",
     "Tallinn"
    ],
    [
     "Latvia",
     "Riga"
    ],
    [
     "Lithuania",
     "Vilnius"
    ],
    [
     "Slovakia",
     "Bratislava"
    ],
    [
     "Slovenia",
     "Ljubljana"
    ]
   ]
  },
  {
   "id": "geo.cap.asia",
   "name": "Capitals: Asia & Middle East",
   "subject": "geography",
   "forward": "What is the capital of %@?",
   "reverse": "%@ is the capital of…",
   "pairs": [
    [
     "Japan",
     "Tokyo"
    ],
    [
     "China",
     "Beijing"
    ],
    [
     "South Korea",
     "Seoul"
    ],
    [
     "India",
     "New Delhi"
    ],
    [
     "Pakistan",
     "Islamabad"
    ],
    [
     "Bangladesh",
     "Dhaka"
    ],
    [
     "Thailand",
     "Bangkok"
    ],
    [
     "Vietnam",
     "Hanoi"
    ],
    [
     "Philippines",
     "Manila"
    ],
    [
     "Indonesia",
     "Jakarta"
    ],
    [
     "Malaysia",
     "Kuala Lumpur"
    ],
    [
     "Mongolia",
     "Ulaanbaatar"
    ],
    [
     "Nepal",
     "Kathmandu"
    ],
    [
     "Afghanistan",
     "Kabul"
    ],
    [
     "Iran",
     "Tehran"
    ],
    [
     "Iraq",
     "Baghdad"
    ],
    [
     "Saudi Arabia",
     "Riyadh"
    ],
    [
     "Israel",
     "Jerusalem"
    ],
    [
     "Jordan",
     "Amman"
    ],
    [
     "Syria",
     "Damascus"
    ],
    [
     "Lebanon",
     "Beirut"
    ],
    [
     "Turkey",
     "Ankara"
    ],
    [
     "Kazakhstan",
     "Astana"
    ],
    [
     "Uzbekistan",
     "Tashkent"
    ],
    [
     "Qatar",
     "Doha"
    ],
    [
     "United Arab Emirates",
     "Abu Dhabi"
    ],
    [
     "Sri Lanka",
     "Sri Jayawardenepura Kotte"
    ],
    [
     "Myanmar",
     "Naypyidaw"
    ],
    [
     "Cambodia",
     "Phnom Penh"
    ],
    [
     "Laos",
     "Vientiane"
    ]
   ]
  },
  {
   "id": "geo.cap.africa",
   "name": "Capitals: Africa",
   "subject": "geography",
   "forward": "What is the capital of %@?",
   "reverse": "%@ is the capital of…",
   "pairs": [
    [
     "Egypt",
     "Cairo"
    ],
    [
     "Nigeria",
     "Abuja"
    ],
    [
     "Kenya",
     "Nairobi"
    ],
    [
     "Ethiopia",
     "Addis Ababa"
    ],
    [
     "Ghana",
     "Accra"
    ],
    [
     "Morocco",
     "Rabat"
    ],
    [
     "Algeria",
     "Algiers"
    ],
    [
     "Tunisia",
     "Tunis"
    ],
    [
     "Libya",
     "Tripoli"
    ],
    [
     "Sudan",
     "Khartoum"
    ],
    [
     "Uganda",
     "Kampala"
    ],
    [
     "Tanzania",
     "Dodoma"
    ],
    [
     "Rwanda",
     "Kigali"
    ],
    [
     "Senegal",
     "Dakar"
    ],
    [
     "Mali",
     "Bamako"
    ],
    [
     "Zimbabwe",
     "Harare"
    ],
    [
     "Zambia",
     "Lusaka"
    ],
    [
     "Angola",
     "Luanda"
    ],
    [
     "Mozambique",
     "Maputo"
    ],
    [
     "Madagascar",
     "Antananarivo"
    ],
    [
     "Cameroon",
     "Yaoundé"
    ],
    [
     "Somalia",
     "Mogadishu"
    ],
    [
     "Botswana",
     "Gaborone"
    ],
    [
     "Namibia",
     "Windhoek"
    ],
    [
     "Democratic Republic of the Congo",
     "Kinshasa"
    ]
   ]
  },
  {
   "id": "geo.cap.americas",
   "name": "Capitals: The Americas",
   "subject": "geography",
   "forward": "What is the capital of %@?",
   "reverse": "%@ is the capital of…",
   "pairs": [
    [
     "United States",
     "Washington, D.C."
    ],
    [
     "Canada",
     "Ottawa"
    ],
    [
     "Mexico",
     "Mexico City"
    ],
    [
     "Brazil",
     "Brasília"
    ],
    [
     "Argentina",
     "Buenos Aires"
    ],
    [
     "Chile",
     "Santiago"
    ],
    [
     "Peru",
     "Lima"
    ],
    [
     "Colombia",
     "Bogotá"
    ],
    [
     "Venezuela",
     "Caracas"
    ],
    [
     "Ecuador",
     "Quito"
    ],
    [
     "Bolivia",
     "Sucre"
    ],
    [
     "Paraguay",
     "Asunción"
    ],
    [
     "Uruguay",
     "Montevideo"
    ],
    [
     "Cuba",
     "Havana"
    ],
    [
     "Jamaica",
     "Kingston"
    ],
    [
     "Haiti",
     "Port-au-Prince"
    ],
    [
     "Dominican Republic",
     "Santo Domingo"
    ],
    [
     "Guatemala",
     "Guatemala City"
    ],
    [
     "Honduras",
     "Tegucigalpa"
    ],
    [
     "Nicaragua",
     "Managua"
    ],
    [
     "Costa Rica",
     "San José"
    ],
    [
     "Panama",
     "Panama City"
    ],
    [
     "El Salvador",
     "San Salvador"
    ],
    [
     "Bahamas",
     "Nassau"
    ],
    [
     "Guyana",
     "Georgetown"
    ]
   ]
  },
  {
   "id": "geo.cap.oceania",
   "name": "Capitals: Oceania",
   "subject": "geography",
   "forward": "What is the capital of %@?",
   "reverse": "%@ is the capital of…",
   "pairs": [
    [
     "Australia",
     "Canberra"
    ],
    [
     "New Zealand",
     "Wellington"
    ],
    [
     "Fiji",
     "Suva"
    ],
    [
     "Papua New Guinea",
     "Port Moresby"
    ],
    [
     "Samoa",
     "Apia"
    ],
    [
     "Tonga",
     "Nukuʻalofa"
    ],
    [
     "Vanuatu",
     "Port Vila"
    ],
    [
     "Solomon Islands",
     "Honiara"
    ],
    [
     "Palau",
     "Ngerulmud"
    ],
    [
     "Kiribati",
     "South Tarawa"
    ]
   ]
  },
  {
   "id": "geo.states.1",
   "name": "U.S. State Capitals I",
   "subject": "geography",
   "forward": "What is the capital of %@?",
   "reverse": "%@ is the capital of which state?",
   "pairs": [
    [
     "Alabama",
     "Montgomery"
    ],
    [
     "Alaska",
     "Juneau"
    ],
    [
     "Arizona",
     "Phoenix"
    ],
    [
     "Arkansas",
     "Little Rock"
    ],
    [
     "California",
     "Sacramento"
    ],
    [
     "Colorado",
     "Denver"
    ],
    [
     "Connecticut",
     "Hartford"
    ],
    [
     "Delaware",
     "Dover"
    ],
    [
     "Florida",
     "Tallahassee"
    ],
    [
     "Georgia",
     "Atlanta"
    ],
    [
     "Hawaii",
     "Honolulu"
    ],
    [
     "Idaho",
     "Boise"
    ],
    [
     "Illinois",
     "Springfield"
    ],
    [
     "Indiana",
     "Indianapolis"
    ],
    [
     "Iowa",
     "Des Moines"
    ],
    [
     "Kansas",
     "Topeka"
    ],
    [
     "Kentucky",
     "Frankfort"
    ],
    [
     "Louisiana",
     "Baton Rouge"
    ],
    [
     "Maine",
     "Augusta"
    ],
    [
     "Maryland",
     "Annapolis"
    ],
    [
     "Massachusetts",
     "Boston"
    ],
    [
     "Michigan",
     "Lansing"
    ],
    [
     "Minnesota",
     "Saint Paul"
    ],
    [
     "Mississippi",
     "Jackson"
    ],
    [
     "Missouri",
     "Jefferson City"
    ]
   ]
  },
  {
   "id": "geo.states.2",
   "name": "U.S. State Capitals II",
   "subject": "geography",
   "forward": "What is the capital of %@?",
   "reverse": "%@ is the capital of which state?",
   "pairs": [
    [
     "Montana",
     "Helena"
    ],
    [
     "Nebraska",
     "Lincoln"
    ],
    [
     "Nevada",
     "Carson City"
    ],
    [
     "New Hampshire",
     "Concord"
    ],
    [
     "New Jersey",
     "Trenton"
    ],
    [
     "New Mexico",
     "Santa Fe"
    ],
    [
     "New York",
     "Albany"
    ],
    [
     "North Carolina",
     "Raleigh"
    ],
    [
     "North Dakota",
     "Bismarck"
    ],
    [
     "Ohio",
     "Columbus"
    ],
    [
     "Oklahoma",
     "Oklahoma City"
    ],
    [
     "Oregon",
     "Salem"
    ],
    [
     "Pennsylvania",
     "Harrisburg"
    ],
    [
     "Rhode Island",
     "Providence"
    ],
    [
     "South Carolina",
     "Columbia"
    ],
    [
     "South Dakota",
     "Pierre"
    ],
    [
     "Tennessee",
     "Nashville"
    ],
    [
     "Texas",
     "Austin"
    ],
    [
     "Utah",
     "Salt Lake City"
    ],
    [
     "Vermont",
     "Montpelier"
    ],
    [
     "Virginia",
     "Richmond"
    ],
    [
     "Washington",
     "Olympia"
    ],
    [
     "West Virginia",
     "Charleston"
    ],
    [
     "Wisconsin",
     "Madison"
    ],
    [
     "Wyoming",
     "Cheyenne"
    ]
   ]
  },
  {
   "id": "geo.landmarks",
   "name": "World Landmarks",
   "subject": "geography",
   "forward": "In which country is %@?",
   "reverse": null,
   "pairs": [
    [
     "Machu Picchu",
     "Peru"
    ],
    [
     "the Taj Mahal",
     "India"
    ],
    [
     "Petra",
     "Jordan"
    ],
    [
     "Angkor Wat",
     "Cambodia"
    ],
    [
     "Chichén Itzá",
     "Mexico"
    ],
    [
     "the Colosseum",
     "Italy"
    ],
    [
     "Christ the Redeemer",
     "Brazil"
    ],
    [
     "the Great Wall",
     "China"
    ],
    [
     "Stonehenge",
     "United Kingdom"
    ],
    [
     "the Acropolis",
     "Greece"
    ],
    [
     "the Sagrada Família",
     "Spain"
    ],
    [
     "the Sydney Opera House",
     "Australia"
    ],
    [
     "Mount Kilimanjaro",
     "Tanzania"
    ],
    [
     "the Great Pyramid of Giza",
     "Egypt"
    ],
    [
     "Neuschwanstein Castle",
     "Germany"
    ],
    [
     "Mount Fuji",
     "Japan"
    ],
    [
     "Easter Island's moai",
     "Chile"
    ],
    [
     "the Hagia Sophia",
     "Turkey"
    ],
    [
     "Table Mountain",
     "South Africa"
    ],
    [
     "the Burj Khalifa",
     "United Arab Emirates"
    ]
   ]
  },
  {
   "id": "sci.elements.1",
   "name": "Chemical Elements I",
   "subject": "science",
   "forward": "What is the symbol for %@?",
   "reverse": "Which element has the symbol %@?",
   "pairs": [
    [
     "Hydrogen",
     "H"
    ],
    [
     "Helium",
     "He"
    ],
    [
     "Lithium",
     "Li"
    ],
    [
     "Beryllium",
     "Be"
    ],
    [
     "Boron",
     "B"
    ],
    [
     "Carbon",
     "C"
    ],
    [
     "Nitrogen",
     "N"
    ],
    [
     "Oxygen",
     "O"
    ],
    [
     "Fluorine",
     "F"
    ],
    [
     "Neon",
     "Ne"
    ],
    [
     "Sodium",
     "Na"
    ],
    [
     "Magnesium",
     "Mg"
    ],
    [
     "Aluminum",
     "Al"
    ],
    [
     "Silicon",
     "Si"
    ],
    [
     "Phosphorus",
     "P"
    ],
    [
     "Sulfur",
     "S"
    ],
    [
     "Chlorine",
     "Cl"
    ],
    [
     "Argon",
     "Ar"
    ],
    [
     "Potassium",
     "K"
    ],
    [
     "Calcium",
     "Ca"
    ]
   ]
  },
  {
   "id": "sci.elements.2",
   "name": "Chemical Elements II",
   "subject": "science",
   "forward": "What is the symbol for %@?",
   "reverse": "Which element has the symbol %@?",
   "pairs": [
    [
     "Titanium",
     "Ti"
    ],
    [
     "Chromium",
     "Cr"
    ],
    [
     "Manganese",
     "Mn"
    ],
    [
     "Iron",
     "Fe"
    ],
    [
     "Cobalt",
     "Co"
    ],
    [
     "Nickel",
     "Ni"
    ],
    [
     "Copper",
     "Cu"
    ],
    [
     "Zinc",
     "Zn"
    ],
    [
     "Arsenic",
     "As"
    ],
    [
     "Bromine",
     "Br"
    ],
    [
     "Krypton",
     "Kr"
    ],
    [
     "Silver",
     "Ag"
    ],
    [
     "Tin",
     "Sn"
    ],
    [
     "Iodine",
     "I"
    ],
    [
     "Xenon",
     "Xe"
    ],
    [
     "Platinum",
     "Pt"
    ],
    [
     "Gold",
     "Au"
    ],
    [
     "Mercury",
     "Hg"
    ],
    [
     "Lead",
     "Pb"
    ],
    [
     "Uranium",
     "U"
    ]
   ]
  },
  {
   "id": "sci.bio",
   "name": "Biology Essentials",
   "subject": "science",
   "forward": "What is %@?",
   "reverse": "Which term matches: %@",
   "pairs": [
    [
     "mitochondria",
     "the organelle that produces most of the cell's ATP"
    ],
    [
     "ribosome",
     "the structure that synthesizes proteins"
    ],
    [
     "photosynthesis",
     "converting light, water, and CO₂ into glucose and oxygen"
    ],
    [
     "osmosis",
     "diffusion of water across a semipermeable membrane"
    ],
    [
     "mitosis",
     "cell division producing two identical daughter cells"
    ],
    [
     "meiosis",
     "cell division producing four gametes with half the chromosomes"
    ],
    [
     "DNA",
     "the double-helix molecule that stores genetic information"
    ],
    [
     "enzyme",
     "a protein that speeds up chemical reactions"
    ],
    [
     "homeostasis",
     "maintaining a stable internal environment"
    ],
    [
     "allele",
     "a variant form of a gene"
    ],
    [
     "genotype",
     "an organism's genetic makeup"
    ],
    [
     "phenotype",
     "an organism's observable traits"
    ],
    [
     "natural selection",
     "differential survival and reproduction of better-adapted organisms"
    ],
    [
     "chloroplast",
     "the organelle where photosynthesis occurs"
    ],
    [
     "nucleus",
     "the organelle containing most of a eukaryotic cell's DNA"
    ],
    [
     "prokaryote",
     "a single-celled organism without a nucleus"
    ],
    [
     "ecosystem",
     "a community of organisms interacting with their environment"
    ],
    [
     "producer",
     "an organism that makes its own food"
    ],
    [
     "transcription",
     "copying DNA into messenger RNA"
    ],
    [
     "translation",
     "building a protein from an mRNA sequence"
    ]
   ]
  },
  {
   "id": "sci.chem",
   "name": "Chemistry Concepts",
   "subject": "science",
   "forward": "What is %@?",
   "reverse": "Which term matches: %@",
   "pairs": [
    [
     "an isotope",
     "atoms of an element with different numbers of neutrons"
    ],
    [
     "a mole",
     "6.022 × 10²³ particles of a substance"
    ],
    [
     "pH",
     "a measure of hydrogen-ion concentration (acidity)"
    ],
    [
     "a covalent bond",
     "a bond formed by sharing electrons"
    ],
    [
     "an ionic bond",
     "a bond formed by transfer of electrons"
    ],
    [
     "a catalyst",
     "a substance that speeds a reaction without being consumed"
    ],
    [
     "oxidation",
     "loss of electrons"
    ],
    [
     "reduction",
     "gain of electrons"
    ],
    [
     "an exothermic reaction",
     "a reaction that releases heat"
    ],
    [
     "an endothermic reaction",
     "a reaction that absorbs heat"
    ],
    [
     "electronegativity",
     "an atom's tendency to attract bonding electrons"
    ],
    [
     "a noble gas",
     "an unreactive element in group 18"
    ],
    [
     "molarity",
     "moles of solute per liter of solution"
    ],
    [
     "an alkali metal",
     "a highly reactive element in group 1"
    ],
    [
     "sublimation",
     "a solid turning directly into a gas"
    ]
   ]
  },
  {
   "id": "sci.physics",
   "name": "Physics Units & Laws",
   "subject": "science",
   "forward": "What is %@?",
   "reverse": "Which term matches: %@",
   "pairs": [
    [
     "the newton",
     "the SI unit of force"
    ],
    [
     "the joule",
     "the SI unit of energy"
    ],
    [
     "the watt",
     "the SI unit of power"
    ],
    [
     "the pascal",
     "the SI unit of pressure"
    ],
    [
     "the ohm",
     "the SI unit of electrical resistance"
    ],
    [
     "Newton's first law",
     "an object stays at rest or in motion unless acted on by a net force"
    ],
    [
     "Newton's second law",
     "force equals mass times acceleration"
    ],
    [
     "Newton's third law",
     "every action has an equal and opposite reaction"
    ],
    [
     "Ohm's law",
     "voltage equals current times resistance"
    ],
    [
     "kinetic energy",
     "energy of motion, ½mv²"
    ],
    [
     "potential energy",
     "stored energy due to position"
    ],
    [
     "momentum",
     "mass times velocity"
    ],
    [
     "frequency",
     "number of wave cycles per second"
    ],
    [
     "velocity",
     "speed in a given direction"
    ],
    [
     "acceleration",
     "rate of change of velocity"
    ]
   ]
  },
  {
   "id": "sci.anatomy",
   "name": "Human Anatomy",
   "subject": "science",
   "forward": "What is the job of the %@?",
   "reverse": "Which organ or structure: %@",
   "pairs": [
    [
     "heart",
     "pumps blood through the body"
    ],
    [
     "lungs",
     "exchange oxygen and carbon dioxide"
    ],
    [
     "liver",
     "detoxifies blood and produces bile"
    ],
    [
     "kidneys",
     "filter blood and produce urine"
    ],
    [
     "pancreas",
     "produces insulin and digestive enzymes"
    ],
    [
     "small intestine",
     "absorbs most nutrients from food"
    ],
    [
     "large intestine",
     "absorbs water and forms feces"
    ],
    [
     "stomach",
     "breaks down food with acid and enzymes"
    ],
    [
     "brain",
     "controls the nervous system"
    ],
    [
     "skin",
     "the largest organ; protects the body"
    ],
    [
     "spleen",
     "filters blood and supports immunity"
    ],
    [
     "thyroid",
     "regulates metabolism with hormones"
    ],
    [
     "femur",
     "the longest bone in the human body"
    ],
    [
     "diaphragm",
     "the muscle that drives breathing"
    ]
   ]
  },
  {
   "id": "sci.space",
   "name": "Astronomy",
   "subject": "science",
   "forward": "%@",
   "reverse": null,
   "pairs": [
    [
     "Which planet is closest to the Sun?",
     "Mercury"
    ],
    [
     "Which planet is the largest?",
     "Jupiter"
    ],
    [
     "Which planet has the most prominent rings?",
     "Saturn"
    ],
    [
     "Which planet is known as the Red Planet?",
     "Mars"
    ],
    [
     "Which planet rotates on its side?",
     "Uranus"
    ],
    [
     "Which planet is the hottest?",
     "Venus"
    ],
    [
     "Which planet is farthest from the Sun?",
     "Neptune"
    ],
    [
     "What is the closest star to Earth?",
     "The Sun"
    ],
    [
     "What galaxy do we live in?",
     "The Milky Way"
    ],
    [
     "What is the largest moon in the solar system?",
     "Ganymede"
    ],
    [
     "What is a light-year a measure of?",
     "Distance"
    ],
    [
     "What force keeps planets in orbit?",
     "Gravity"
    ]
   ]
  },
  {
   "id": "hist.us",
   "name": "U.S. History Dates",
   "subject": "history",
   "forward": "In what year: %@?",
   "reverse": null,
   "pairs": [
    [
     "the Declaration of Independence was signed",
     "1776"
    ],
    [
     "the U.S. Constitution was written",
     "1787"
    ],
    [
     "the Louisiana Purchase occurred",
     "1803"
    ],
    [
     "the Civil War began",
     "1861"
    ],
    [
     "the Emancipation Proclamation was issued",
     "1863"
    ],
    [
     "the Civil War ended",
     "1865"
    ],
    [
     "women won the right to vote (19th Amendment)",
     "1920"
    ],
    [
     "the stock market crashed, starting the Great Depression",
     "1929"
    ],
    [
     "Pearl Harbor was attacked",
     "1941"
    ],
    [
     "Brown v. Board of Education was decided",
     "1954"
    ],
    [
     "the Civil Rights Act was passed",
     "1964"
    ],
    [
     "Apollo 11 landed on the Moon",
     "1969"
    ],
    [
     "the September 11 attacks occurred",
     "2001"
    ],
    [
     "the War of 1812 began",
     "1812"
    ],
    [
     "Columbus first reached the Americas",
     "1492"
    ],
    [
     "Jamestown was founded",
     "1607"
    ]
   ]
  },
  {
   "id": "hist.world",
   "name": "World History Dates",
   "subject": "history",
   "forward": "In what year: %@?",
   "reverse": null,
   "pairs": [
    [
     "the Western Roman Empire fell",
     "476"
    ],
    [
     "the Magna Carta was signed",
     "1215"
    ],
    [
     "the printing press was invented by Gutenberg (approx.)",
     "1440"
    ],
    [
     "the French Revolution began",
     "1789"
    ],
    [
     "World War I began",
     "1914"
    ],
    [
     "the Russian Revolution occurred",
     "1917"
    ],
    [
     "World War II began",
     "1939"
    ],
    [
     "World War II ended",
     "1945"
    ],
    [
     "the United Nations was founded",
     "1945"
    ],
    [
     "India gained independence",
     "1947"
    ],
    [
     "the Berlin Wall fell",
     "1989"
    ],
    [
     "the Soviet Union dissolved",
     "1991"
    ],
    [
     "Constantinople fell to the Ottomans",
     "1453"
    ],
    [
     "the Protestant Reformation began",
     "1517"
    ],
    [
     "Napoleon was defeated at Waterloo",
     "1815"
    ]
   ]
  },
  {
   "id": "hist.presidents",
   "name": "U.S. Presidents 1–20",
   "subject": "history",
   "forward": "Who was U.S. President #%@?",
   "reverse": "%@ was President number…",
   "pairs": [
    [
     "1",
     "George Washington"
    ],
    [
     "2",
     "John Adams"
    ],
    [
     "3",
     "Thomas Jefferson"
    ],
    [
     "4",
     "James Madison"
    ],
    [
     "5",
     "James Monroe"
    ],
    [
     "6",
     "John Quincy Adams"
    ],
    [
     "7",
     "Andrew Jackson"
    ],
    [
     "8",
     "Martin Van Buren"
    ],
    [
     "9",
     "William Henry Harrison"
    ],
    [
     "10",
     "John Tyler"
    ],
    [
     "11",
     "James K. Polk"
    ],
    [
     "12",
     "Zachary Taylor"
    ],
    [
     "13",
     "Millard Fillmore"
    ],
    [
     "14",
     "Franklin Pierce"
    ],
    [
     "15",
     "James Buchanan"
    ],
    [
     "16",
     "Abraham Lincoln"
    ],
    [
     "17",
     "Andrew Johnson"
    ],
    [
     "18",
     "Ulysses S. Grant"
    ],
    [
     "19",
     "Rutherford B. Hayes"
    ],
    [
     "20",
     "James A. Garfield"
    ]
   ]
  },
  {
   "id": "hist.civics",
   "name": "Civics & Government",
   "subject": "history",
   "forward": "What is %@?",
   "reverse": "Which term matches: %@",
   "pairs": [
    [
     "checks and balances",
     "each branch of government can limit the others"
    ],
    [
     "federalism",
     "power divided between national and state governments"
    ],
    [
     "judicial review",
     "courts can strike down unconstitutional laws"
    ],
    [
     "the Bill of Rights",
     "the first ten amendments to the Constitution"
    ],
    [
     "a filibuster",
     "prolonged debate used to delay a Senate vote"
    ],
    [
     "a veto",
     "the president's rejection of a bill"
    ],
    [
     "the Electoral College",
     "the body that formally elects the U.S. president"
    ],
    [
     "impeachment",
     "the House bringing charges against an official"
    ],
    [
     "due process",
     "fair legal procedures before depriving rights"
    ],
    [
     "popular sovereignty",
     "the idea that government power comes from the people"
    ],
    [
     "separation of powers",
     "dividing government into legislative, executive, and judicial branches"
    ],
    [
     "a bicameral legislature",
     "a lawmaking body with two chambers"
    ]
   ]
  },
  {
   "id": "lang.es.1",
   "name": "Spanish Vocab I",
   "subject": "languages",
   "forward": "What does “%@” mean?",
   "reverse": "How do you say “%@” in Spanish?",
   "pairs": [
    [
     "hola",
     "hello"
    ],
    [
     "adiós",
     "goodbye"
    ],
    [
     "gracias",
     "thank you"
    ],
    [
     "por favor",
     "please"
    ],
    [
     "perro",
     "dog"
    ],
    [
     "gato",
     "cat"
    ],
    [
     "casa",
     "house"
    ],
    [
     "agua",
     "water"
    ],
    [
     "comida",
     "food"
    ],
    [
     "libro",
     "book"
    ],
    [
     "escuela",
     "school"
    ],
    [
     "amigo",
     "friend"
    ],
    [
     "familia",
     "family"
    ],
    [
     "ciudad",
     "city"
    ],
    [
     "tiempo",
     "time / weather"
    ],
    [
     "trabajo",
     "work"
    ],
    [
     "dinero",
     "money"
    ],
    [
     "rojo",
     "red"
    ],
    [
     "azul",
     "blue"
    ],
    [
     "verde",
     "green"
    ],
    [
     "grande",
     "big"
    ],
    [
     "pequeño",
     "small"
    ],
    [
     "feliz",
     "happy"
    ],
    [
     "triste",
     "sad"
    ],
    [
     "rápido",
     "fast"
    ]
   ]
  },
  {
   "id": "lang.es.2",
   "name": "Spanish Vocab II",
   "subject": "languages",
   "forward": "What does “%@” mean?",
   "reverse": "How do you say “%@” in Spanish?",
   "pairs": [
    [
     "hablar",
     "to speak"
    ],
    [
     "comer",
     "to eat"
    ],
    [
     "beber",
     "to drink"
    ],
    [
     "vivir",
     "to live"
    ],
    [
     "escribir",
     "to write"
    ],
    [
     "leer",
     "to read"
    ],
    [
     "correr",
     "to run"
    ],
    [
     "dormir",
     "to sleep"
    ],
    [
     "querer",
     "to want / to love"
    ],
    [
     "poder",
     "to be able to"
    ],
    [
     "tener",
     "to have"
    ],
    [
     "hacer",
     "to do / to make"
    ],
    [
     "ir",
     "to go"
    ],
    [
     "venir",
     "to come"
    ],
    [
     "saber",
     "to know (facts)"
    ],
    [
     "conocer",
     "to know (people, places)"
    ],
    [
     "ayer",
     "yesterday"
    ],
    [
     "mañana",
     "tomorrow / morning"
    ],
    [
     "siempre",
     "always"
    ],
    [
     "nunca",
     "never"
    ]
   ]
  },
  {
   "id": "lang.fr",
   "name": "French Vocab",
   "subject": "languages",
   "forward": "What does “%@” mean?",
   "reverse": "How do you say “%@” in French?",
   "pairs": [
    [
     "bonjour",
     "hello"
    ],
    [
     "merci",
     "thank you"
    ],
    [
     "s'il vous plaît",
     "please"
    ],
    [
     "au revoir",
     "goodbye"
    ],
    [
     "chien",
     "dog"
    ],
    [
     "chat",
     "cat"
    ],
    [
     "maison",
     "house"
    ],
    [
     "eau",
     "water"
    ],
    [
     "pain",
     "bread"
    ],
    [
     "livre",
     "book"
    ],
    [
     "école",
     "school"
    ],
    [
     "ami",
     "friend"
    ],
    [
     "voiture",
     "car"
    ],
    [
     "rouge",
     "red"
    ],
    [
     "bleu",
     "blue"
    ],
    [
     "grand",
     "tall / big"
    ],
    [
     "petit",
     "small"
    ],
    [
     "heureux",
     "happy"
    ],
    [
     "manger",
     "to eat"
    ],
    [
     "boire",
     "to drink"
    ],
    [
     "parler",
     "to speak"
    ],
    [
     "aller",
     "to go"
    ],
    [
     "avoir",
     "to have"
    ],
    [
     "être",
     "to be"
    ],
    [
     "faire",
     "to do / to make"
    ]
   ]
  },
  {
   "id": "lang.de",
   "name": "German Vocab",
   "subject": "languages",
   "forward": "What does “%@” mean?",
   "reverse": "How do you say “%@” in German?",
   "pairs": [
    [
     "hallo",
     "hello"
    ],
    [
     "danke",
     "thank you"
    ],
    [
     "bitte",
     "please"
    ],
    [
     "tschüss",
     "bye"
    ],
    [
     "Hund",
     "dog"
    ],
    [
     "Katze",
     "cat"
    ],
    [
     "Haus",
     "house"
    ],
    [
     "Wasser",
     "water"
    ],
    [
     "Brot",
     "bread"
    ],
    [
     "Buch",
     "book"
    ],
    [
     "Schule",
     "school"
    ],
    [
     "Freund",
     "friend"
    ],
    [
     "Auto",
     "car"
    ],
    [
     "rot",
     "red"
    ],
    [
     "blau",
     "blue"
    ],
    [
     "groß",
     "big"
    ],
    [
     "klein",
     "small"
    ],
    [
     "glücklich",
     "happy"
    ],
    [
     "essen",
     "to eat"
    ],
    [
     "trinken",
     "to drink"
    ],
    [
     "sprechen",
     "to speak"
    ],
    [
     "gehen",
     "to go"
    ],
    [
     "haben",
     "to have"
    ],
    [
     "sein",
     "to be"
    ]
   ]
  },
  {
   "id": "hum.lit",
   "name": "Literature: Who Wrote It?",
   "subject": "humanities",
   "forward": "Who wrote “%@”?",
   "reverse": "Which work is by %@?",
   "pairs": [
    [
     "1984",
     "George Orwell"
    ],
    [
     "Pride and Prejudice",
     "Jane Austen"
    ],
    [
     "To Kill a Mockingbird",
     "Harper Lee"
    ],
    [
     "The Great Gatsby",
     "F. Scott Fitzgerald"
    ],
    [
     "Moby-Dick",
     "Herman Melville"
    ],
    [
     "Hamlet",
     "William Shakespeare"
    ],
    [
     "The Odyssey",
     "Homer"
    ],
    [
     "Frankenstein",
     "Mary Shelley"
    ],
    [
     "Beloved",
     "Toni Morrison"
    ],
    [
     "One Hundred Years of Solitude",
     "Gabriel García Márquez"
    ],
    [
     "The Catcher in the Rye",
     "J. D. Salinger"
    ],
    [
     "Crime and Punishment",
     "Fyodor Dostoevsky"
    ],
    [
     "War and Peace",
     "Leo Tolstoy"
    ],
    [
     "Things Fall Apart",
     "Chinua Achebe"
    ],
    [
     "The Scarlet Letter",
     "Nathaniel Hawthorne"
    ],
    [
     "Of Mice and Men",
     "John Steinbeck"
    ],
    [
     "Brave New World",
     "Aldous Huxley"
    ],
    [
     "Jane Eyre",
     "Charlotte Brontë"
    ],
    [
     "Wuthering Heights",
     "Emily Brontë"
    ],
    [
     "The Divine Comedy",
     "Dante Alighieri"
    ],
    [
     "Don Quixote",
     "Miguel de Cervantes"
    ],
    [
     "The Adventures of Huckleberry Finn",
     "Mark Twain"
    ],
    [
     "Their Eyes Were Watching God",
     "Zora Neale Hurston"
    ],
    [
     "Fahrenheit 451",
     "Ray Bradbury"
    ]
   ]
  },
  {
   "id": "hum.art",
   "name": "Famous Artworks",
   "subject": "humanities",
   "forward": "Who created “%@”?",
   "reverse": "Which work is by %@?",
   "pairs": [
    [
     "Mona Lisa",
     "Leonardo da Vinci"
    ],
    [
     "The Starry Night",
     "Vincent van Gogh"
    ],
    [
     "The Persistence of Memory",
     "Salvador Dalí"
    ],
    [
     "Guernica",
     "Pablo Picasso"
    ],
    [
     "The Scream",
     "Edvard Munch"
    ],
    [
     "Girl with a Pearl Earring",
     "Johannes Vermeer"
    ],
    [
     "The Birth of Venus",
     "Sandro Botticelli"
    ],
    [
     "The Night Watch",
     "Rembrandt"
    ],
    [
     "Water Lilies",
     "Claude Monet"
    ],
    [
     "The Sistine Chapel ceiling",
     "Michelangelo"
    ],
    [
     "American Gothic",
     "Grant Wood"
    ],
    [
     "The Kiss",
     "Gustav Klimt"
    ],
    [
     "The Great Wave off Kanagawa",
     "Katsushika Hokusai"
    ],
    [
     "Campbell's Soup Cans",
     "Andy Warhol"
    ],
    [
     "The School of Athens",
     "Raphael"
    ],
    [
     "Liberty Leading the People",
     "Eugène Delacroix"
    ]
   ]
  },
  {
   "id": "hum.myth",
   "name": "Greek Mythology",
   "subject": "humanities",
   "forward": "What is %@ the god/goddess of?",
   "reverse": "Who is the Greek deity of %@?",
   "pairs": [
    [
     "Zeus",
     "the sky and thunder"
    ],
    [
     "Poseidon",
     "the sea"
    ],
    [
     "Hades",
     "the underworld"
    ],
    [
     "Athena",
     "wisdom and war strategy"
    ],
    [
     "Apollo",
     "the sun, music, and prophecy"
    ],
    [
     "Artemis",
     "the hunt and the moon"
    ],
    [
     "Aphrodite",
     "love and beauty"
    ],
    [
     "Ares",
     "war"
    ],
    [
     "Hermes",
     "messengers, travel, and thieves"
    ],
    [
     "Hephaestus",
     "fire and the forge"
    ],
    [
     "Demeter",
     "the harvest and agriculture"
    ],
    [
     "Dionysus",
     "wine and festivity"
    ],
    [
     "Hera",
     "marriage and family"
    ],
    [
     "Hestia",
     "the hearth and home"
    ]
   ]
  },
  {
   "id": "hum.philo",
   "name": "Philosophers",
   "subject": "humanities",
   "forward": "Which idea is %@ known for?",
   "reverse": "Who is known for: %@?",
   "pairs": [
    [
     "Socrates",
     "questioning to expose ignorance (the Socratic method)"
    ],
    [
     "Plato",
     "the theory of Forms"
    ],
    [
     "Aristotle",
     "virtue as the mean between extremes"
    ],
    [
     "René Descartes",
     "“I think, therefore I am”"
    ],
    [
     "John Locke",
     "natural rights to life, liberty, and property"
    ],
    [
     "Thomas Hobbes",
     "life without government is “nasty, brutish, and short”"
    ],
    [
     "Immanuel Kant",
     "the categorical imperative"
    ],
    [
     "John Stuart Mill",
     "utilitarianism: the greatest good for the greatest number"
    ],
    [
     "Friedrich Nietzsche",
     "“God is dead” and the Übermensch"
    ],
    [
     "Jean-Paul Sartre",
     "“existence precedes essence”"
    ],
    [
     "Confucius",
     "filial piety and social harmony"
    ],
    [
     "Karl Marx",
     "history as class struggle"
    ]
   ]
  },
  {
   "id": "hum.lit.devices",
   "name": "Literary Devices",
   "subject": "humanities",
   "forward": "What is %@?",
   "reverse": "Which device: %@",
   "pairs": [
    [
     "a metaphor",
     "a direct comparison without “like” or “as”"
    ],
    [
     "a simile",
     "a comparison using “like” or “as”"
    ],
    [
     "personification",
     "giving human traits to nonhuman things"
    ],
    [
     "alliteration",
     "repetition of initial consonant sounds"
    ],
    [
     "hyperbole",
     "deliberate exaggeration"
    ],
    [
     "irony",
     "a contrast between expectation and reality"
    ],
    [
     "foreshadowing",
     "hints about what will happen later"
    ],
    [
     "onomatopoeia",
     "a word that imitates a sound"
    ],
    [
     "an allusion",
     "an indirect reference to a well-known work or event"
    ],
    [
     "an oxymoron",
     "two contradictory terms placed together"
    ],
    [
     "imagery",
     "descriptive language appealing to the senses"
    ],
    [
     "a paradox",
     "a seemingly contradictory statement that reveals a truth"
    ]
   ]
  },
  {
   "id": "tech.cs",
   "name": "CS Fundamentals",
   "subject": "tech",
   "forward": "What is %@?",
   "reverse": "Which term matches: %@",
   "pairs": [
    [
     "an algorithm",
     "a step-by-step procedure for solving a problem"
    ],
    [
     "a variable",
     "a named storage location for a value"
    ],
    [
     "recursion",
     "a function that calls itself"
    ],
    [
     "an array",
     "an ordered collection of elements accessed by index"
    ],
    [
     "a hash table",
     "a structure mapping keys to values via a hash function"
    ],
    [
     "a stack",
     "a last-in, first-out (LIFO) structure"
    ],
    [
     "a queue",
     "a first-in, first-out (FIFO) structure"
    ],
    [
     "a compiler",
     "translates source code into machine code"
    ],
    [
     "an API",
     "a defined interface for software components to communicate"
    ],
    [
     "a boolean",
     "a value that is either true or false"
    ],
    [
     "encryption",
     "encoding data so only authorized parties can read it"
    ],
    [
     "a binary tree",
     "a structure where each node has at most two children"
    ],
    [
     "an operating system",
     "software that manages hardware and runs programs"
    ],
    [
     "a bug",
     "an error in a program"
    ]
   ]
  },
  {
   "id": "tech.bigo",
   "name": "Big-O Complexity",
   "subject": "tech",
   "forward": "What is the typical time complexity of %@?",
   "reverse": null,
   "pairs": [
    [
     "binary search on a sorted array",
     "O(log n)"
    ],
    [
     "linear search",
     "O(n)"
    ],
    [
     "merge sort",
     "O(n log n)"
    ],
    [
     "bubble sort (worst case)",
     "O(n²)"
    ],
    [
     "hash table lookup (average)",
     "O(1)"
    ],
    [
     "accessing an array element by index",
     "O(1)"
    ],
    [
     "generating all subsets of a set",
     "O(2ⁿ)"
    ]
   ]
  },
  {
   "id": "soc.psych",
   "name": "Psychology Terms",
   "subject": "social",
   "forward": "What is %@?",
   "reverse": "Which term matches: %@",
   "pairs": [
    [
     "classical conditioning",
     "learning by associating two stimuli (Pavlov)"
    ],
    [
     "operant conditioning",
     "learning through rewards and punishments (Skinner)"
    ],
    [
     "cognitive dissonance",
     "discomfort from holding conflicting beliefs"
    ],
    [
     "confirmation bias",
     "favoring information that confirms existing beliefs"
    ],
    [
     "the placebo effect",
     "improvement caused by belief in a treatment"
    ],
    [
     "Maslow's hierarchy",
     "a pyramid of needs from physiological to self-actualization"
    ],
    [
     "the bystander effect",
     "people are less likely to help when others are present"
    ],
    [
     "neuroplasticity",
     "the brain's ability to reorganize itself"
    ],
    [
     "short-term memory",
     "holding a small amount of information briefly"
    ],
    [
     "extrinsic motivation",
     "doing something for an outside reward"
    ],
    [
     "intrinsic motivation",
     "doing something because it is rewarding in itself"
    ],
    [
     "the Dunning–Kruger effect",
     "low-skill people overestimating their ability"
    ]
   ]
  },
  {
   "id": "biz.econ",
   "name": "Economics Terms",
   "subject": "business",
   "forward": "What is %@?",
   "reverse": "Which term matches: %@",
   "pairs": [
    [
     "supply and demand",
     "the relationship that sets market prices"
    ],
    [
     "inflation",
     "a general rise in prices over time"
    ],
    [
     "GDP",
     "the total value of goods and services a country produces"
    ],
    [
     "opportunity cost",
     "the value of the next-best alternative given up"
    ],
    [
     "a monopoly",
     "a market with a single seller"
    ],
    [
     "elasticity",
     "how responsive quantity is to a change in price"
    ],
    [
     "a recession",
     "a significant decline in economic activity"
    ],
    [
     "fiscal policy",
     "government use of taxes and spending"
    ],
    [
     "monetary policy",
     "central bank control of money supply and interest rates"
    ],
    [
     "comparative advantage",
     "producing at a lower opportunity cost than others"
    ],
    [
     "a tariff",
     "a tax on imported goods"
    ],
    [
     "scarcity",
     "limited resources versus unlimited wants"
    ]
   ]
  },
  {
   "id": "biz.finance",
   "name": "Personal Finance",
   "subject": "business",
   "forward": "What is %@?",
   "reverse": "Which term matches: %@",
   "pairs": [
    [
     "compound interest",
     "interest earned on both principal and past interest"
    ],
    [
     "a budget",
     "a plan for income and spending"
    ],
    [
     "a credit score",
     "a number rating how reliably you repay debt"
    ],
    [
     "an index fund",
     "a fund that tracks a market index"
    ],
    [
     "diversification",
     "spreading investments to reduce risk"
    ],
    [
     "an emergency fund",
     "savings set aside for unexpected expenses"
    ],
    [
     "APR",
     "the yearly cost of borrowing, including fees"
    ],
    [
     "a Roth IRA",
     "a retirement account funded with after-tax money"
    ],
    [
     "net worth",
     "assets minus liabilities"
    ],
    [
     "a stock",
     "a share of ownership in a company"
    ],
    [
     "a bond",
     "a loan to a government or company that pays interest"
    ]
   ]
  }
 ],
 "readingWriting": [
  {
   "id": "sat.boundaries",
   "name": "Boundaries: Punctuation",
   "questions": [
    {
     "id": "sat.boundaries#1",
     "prompt": "The museum's newest exhibit features artifacts from three ancient ______ Egypt, Mesopotamia, and the Indus Valley.",
     "answer": "civilizations:",
     "wrong": [
      "civilizations,",
      "civilizations;",
      "civilizations"
     ],
     "explanation": "A colon introduces a list that explains what came before it."
    },
    {
     "id": "sat.boundaries#2",
     "prompt": "Marie Curie won two Nobel ______ she remains the only person honored in two different sciences.",
     "answer": "Prizes;",
     "wrong": [
      "Prizes,",
      "Prizes",
      "Prizes and,"
     ],
     "explanation": "Two independent clauses need a semicolon (a comma alone creates a comma splice)."
    },
    {
     "id": "sat.boundaries#3",
     "prompt": "The novel, which was published in ______ became an instant bestseller.",
     "answer": "1925,",
     "wrong": [
      "1925",
      "1925;",
      "1925:"
     ],
     "explanation": "The nonessential clause opened with a comma must close with a comma."
    },
    {
     "id": "sat.boundaries#4",
     "prompt": "Researchers studied the ______ tail feathers to understand how the birds attract mates.",
     "answer": "peacocks'",
     "wrong": [
      "peacocks",
      "peacocks's",
      "peacock"
     ],
     "explanation": "Plural possessive (many peacocks) takes an apostrophe after the s."
    },
    {
     "id": "sat.boundaries#5",
     "prompt": "Although the experiment ______ the team published its data anyway.",
     "answer": "failed,",
     "wrong": [
      "failed;",
      "failed.",
      "failed:"
     ],
     "explanation": "A dependent clause (\"Although…\") joins the main clause with a comma."
    },
    {
     "id": "sat.boundaries#6",
     "prompt": "The chef insisted on one rule above all ______ never serve a dish you would not eat yourself.",
     "answer": "others:",
     "wrong": [
      "others,",
      "others",
      "others, and"
     ],
     "explanation": "A colon introduces an explanation or elaboration of \"one rule.\""
    },
    {
     "id": "sat.boundaries#7",
     "prompt": "Octopuses are remarkably ______ they can solve puzzles and open jars.",
     "answer": "intelligent—",
     "wrong": [
      "intelligent,",
      "intelligent",
      "intelligent and,"
     ],
     "explanation": "A dash (like a colon) can join a clause to one that explains it; a comma would be a splice."
    },
    {
     "id": "sat.boundaries#8",
     "prompt": "The city's ______ built in 1890, still carries thousands of commuters each day.",
     "answer": "bridge,",
     "wrong": [
      "bridge",
      "bridge;",
      "bridge:"
     ],
     "explanation": "A comma sets off the descriptive phrase \"built in 1890.\""
    }
   ]
  },
  {
   "id": "sat.agreement",
   "name": "Subject-Verb Agreement",
   "questions": [
    {
     "id": "sat.agreement#1",
     "prompt": "The collection of rare coins ______ displayed in the east wing.",
     "answer": "is",
     "wrong": [
      "are",
      "were",
      "have been"
     ],
     "explanation": "The subject is \"collection\" (singular), not \"coins.\""
    },
    {
     "id": "sat.agreement#2",
     "prompt": "Neither the players nor the coach ______ happy with the referee's decision.",
     "answer": "was",
     "wrong": [
      "were",
      "are",
      "have been"
     ],
     "explanation": "With neither/nor, the verb agrees with the nearer subject: \"coach.\""
    },
    {
     "id": "sat.agreement#3",
     "prompt": "Each of the paintings ______ a hidden signature.",
     "answer": "contains",
     "wrong": [
      "contain",
      "are containing",
      "have contained"
     ],
     "explanation": "\"Each\" is singular."
    },
    {
     "id": "sat.agreement#4",
     "prompt": "The data from the recent surveys ______ that commuting times have increased.",
     "answer": "suggest",
     "wrong": [
      "suggests",
      "is suggesting",
      "has suggested"
     ],
     "explanation": "On the SAT, \"data\" is treated as plural."
    },
    {
     "id": "sat.agreement#5",
     "prompt": "Among the island's most famous attractions ______ a lighthouse built in 1802.",
     "answer": "is",
     "wrong": [
      "are",
      "were",
      "have been"
     ],
     "explanation": "Inverted sentence: the subject \"a lighthouse\" follows the verb."
    },
    {
     "id": "sat.agreement#6",
     "prompt": "The number of students applying to college ______ risen each year.",
     "answer": "has",
     "wrong": [
      "have",
      "are",
      "were"
     ],
     "explanation": "\"The number\" is singular (\"a number\" would be plural)."
    }
   ]
  },
  {
   "id": "sat.tense",
   "name": "Verb Tense & Form",
   "questions": [
    {
     "id": "sat.tense#1",
     "prompt": "By the time the rescue team arrived, the hikers ______ for two days.",
     "answer": "had been waiting",
     "wrong": [
      "have been waiting",
      "are waiting",
      "will wait"
     ],
     "explanation": "Past perfect progressive for an action continuing up to a past moment."
    },
    {
     "id": "sat.tense#2",
     "prompt": "In 1969, Neil Armstrong ______ onto the surface of the Moon.",
     "answer": "stepped",
     "wrong": [
      "steps",
      "has stepped",
      "will step"
     ],
     "explanation": "Simple past for a completed event at a specific past time."
    },
    {
     "id": "sat.tense#3",
     "prompt": "Scientists predict that sea levels ______ significantly by 2100.",
     "answer": "will rise",
     "wrong": [
      "rose",
      "had risen",
      "have rose"
     ],
     "explanation": "Future tense for a prediction."
    },
    {
     "id": "sat.tense#4",
     "prompt": "She has ______ three marathons this year.",
     "answer": "run",
     "wrong": [
      "ran",
      "runned",
      "running"
     ],
     "explanation": "\"Has\" takes the past participle \"run.\""
    },
    {
     "id": "sat.tense#5",
     "prompt": "When the bell rang, the students ______ their books and left.",
     "answer": "closed",
     "wrong": [
      "close",
      "have closed",
      "are closing"
     ],
     "explanation": "Keep tense consistent with \"rang.\""
    }
   ]
  },
  {
   "id": "sat.pronouns",
   "name": "Pronouns & Modifiers",
   "questions": [
    {
     "id": "sat.pronouns#1",
     "prompt": "The committee announced ______ decision after a long debate.",
     "answer": "its",
     "wrong": [
      "their",
      "it's",
      "they're"
     ],
     "explanation": "\"Committee\" is a singular collective noun."
    },
    {
     "id": "sat.pronouns#2",
     "prompt": "Between you and ______, the plan is flawed.",
     "answer": "me",
     "wrong": [
      "I",
      "myself",
      "mine"
     ],
     "explanation": "Objects of a preposition use the objective case."
    },
    {
     "id": "sat.pronouns#3",
     "prompt": "Walking through the forest, ______.",
     "answer": "we heard a woodpecker tapping",
     "wrong": [
      "a woodpecker's tapping could be heard",
      "the tapping of a woodpecker was heard",
      "there was a woodpecker tapping"
     ],
     "explanation": "The modifier \"Walking through the forest\" must describe the subject that follows it: \"we.\""
    },
    {
     "id": "sat.pronouns#4",
     "prompt": "The tourists and ______ guide boarded the bus.",
     "answer": "their",
     "wrong": [
      "there",
      "they're",
      "its"
     ],
     "explanation": "Plural possessive pronoun."
    },
    {
     "id": "sat.pronouns#5",
     "prompt": "Having finished the report, ______.",
     "answer": "Priya submitted it to her manager",
     "wrong": [
      "the report was submitted by Priya",
      "it was submitted to the manager",
      "the manager received the report"
     ],
     "explanation": "The person who finished the report must come right after the comma."
    }
   ]
  },
  {
   "id": "sat.transitions",
   "name": "Transitions",
   "questions": [
    {
     "id": "sat.transitions#1",
     "prompt": "The drug showed promise in early trials. ______, later studies revealed serious side effects.",
     "answer": "However",
     "wrong": [
      "Similarly",
      "Therefore",
      "For example"
     ],
     "explanation": "Contrast between promise and side effects."
    },
    {
     "id": "sat.transitions#2",
     "prompt": "Bees are vital to agriculture. ______, they pollinate roughly a third of the crops we eat.",
     "answer": "In fact",
     "wrong": [
      "Nevertheless",
      "In contrast",
      "Meanwhile"
     ],
     "explanation": "The second sentence emphasizes and supports the first."
    },
    {
     "id": "sat.transitions#3",
     "prompt": "The town's population doubled in a decade. ______, demand for housing soared.",
     "answer": "As a result",
     "wrong": [
      "Nonetheless",
      "Likewise",
      "Instead"
     ],
     "explanation": "Cause and effect."
    },
    {
     "id": "sat.transitions#4",
     "prompt": "Some critics dismissed the film as shallow. ______, audiences flocked to theaters to see it.",
     "answer": "Still",
     "wrong": [
      "Thus",
      "Specifically",
      "Furthermore"
     ],
     "explanation": "Contrast: despite the criticism."
    },
    {
     "id": "sat.transitions#5",
     "prompt": "The artist worked mainly in oils. ______, she experimented with watercolor late in life.",
     "answer": "Later",
     "wrong": [
      "Consequently",
      "In other words",
      "Similarly"
     ],
     "explanation": "Time sequence shift."
    },
    {
     "id": "sat.transitions#6",
     "prompt": "Frogs absorb water through their skin. ______, they are highly sensitive to pollutants.",
     "answer": "Consequently",
     "wrong": [
      "However",
      "Previously",
      "By contrast"
     ],
     "explanation": "The permeable skin causes sensitivity."
    }
   ]
  },
  {
   "id": "sat.wordsincontext",
   "name": "Words in Context",
   "questions": [
    {
     "id": "sat.wordsincontext#1",
     "prompt": "The senator's speech was so ______ that even her opponents admitted she had made a convincing case.",
     "answer": "compelling",
     "wrong": [
      "tedious",
      "ambiguous",
      "trivial"
     ],
     "explanation": "Opponents conceding the case implies persuasive."
    },
    {
     "id": "sat.wordsincontext#2",
     "prompt": "Though the scientist was usually ______, she spoke at length about her discovery.",
     "answer": "reticent",
     "wrong": [
      "garrulous",
      "boisterous",
      "candid"
     ],
     "explanation": "\"Though\" signals contrast with speaking at length."
    },
    {
     "id": "sat.wordsincontext#3",
     "prompt": "The fossil record for the species is ______: only a few fragments have ever been found.",
     "answer": "sparse",
     "wrong": [
      "abundant",
      "pristine",
      "redundant"
     ],
     "explanation": "Only a few fragments means scarce."
    },
    {
     "id": "sat.wordsincontext#4",
     "prompt": "The author's style is ______; she uses as few words as possible.",
     "answer": "terse",
     "wrong": [
      "florid",
      "verbose",
      "ornate"
     ],
     "explanation": "Few words = terse."
    },
    {
     "id": "sat.wordsincontext#5",
     "prompt": "The reforms were meant to ______ corruption, but they ended up making it worse.",
     "answer": "curb",
     "wrong": [
      "foster",
      "exacerbate",
      "celebrate"
     ],
     "explanation": "\"But… worse\" contrasts with the intended effect: to restrain."
    },
    {
     "id": "sat.wordsincontext#6",
     "prompt": "Her ______ approach to research—checking every source twice—earned her colleagues' respect.",
     "answer": "meticulous",
     "wrong": [
      "careless",
      "haphazard",
      "cursory"
     ],
     "explanation": "Checking twice = extremely careful."
    },
    {
     "id": "sat.wordsincontext#7",
     "prompt": "The evidence was ______, so the jury could not reach a clear verdict.",
     "answer": "equivocal",
     "wrong": [
      "conclusive",
      "irrefutable",
      "definitive"
     ],
     "explanation": "Unclear evidence prevents a clear verdict."
    }
   ]
  },
  {
   "id": "sat.evidence",
   "name": "Central Ideas & Evidence",
   "questions": [
    {
     "id": "sat.evidence#1",
     "prompt": "A study found that students who slept 8+ hours scored higher on memory tests than those who slept 5 hours. Which choice best states the main finding?",
     "answer": "More sleep was associated with better memory performance.",
     "wrong": [
      "Memory tests cause students to sleep more.",
      "All students should sleep exactly 8 hours.",
      "Sleep has no effect on test scores."
     ],
     "explanation": "The finding is a correlation between sleep and scores; it doesn't prove causation in reverse or prescribe exact hours."
    },
    {
     "id": "sat.evidence#2",
     "prompt": "A researcher claims urban gardens improve neighborhood well-being. Which finding would most directly support this claim?",
     "answer": "Residents near gardens reported lower stress levels than similar residents farther away.",
     "wrong": [
      "Urban gardens require regular watering.",
      "Most urban gardens grow tomatoes.",
      "Gardens were first planted in cities centuries ago."
     ],
     "explanation": "Only this option measures well-being in relation to gardens."
    },
    {
     "id": "sat.evidence#3",
     "prompt": "Text: \"Although the ruins had been studied for a century, new radar scans revealed an entire district no one had suspected.\" What is the main idea?",
     "answer": "New technology uncovered previously unknown parts of the ruins.",
     "wrong": [
      "The ruins were studied for exactly 100 years.",
      "Radar is too inaccurate for archaeology.",
      "The district was built recently."
     ],
     "explanation": "The sentence emphasizes the new discovery made by radar."
    },
    {
     "id": "sat.evidence#4",
     "prompt": "A student wants to emphasize a similarity between two poets. Which choice best accomplishes this goal?",
     "answer": "Like Dickinson, Whitman broke with traditional poetic forms.",
     "wrong": [
      "Dickinson wrote in Massachusetts; Whitman lived in New York.",
      "Whitman published Leaves of Grass in 1855.",
      "Dickinson's poems were published after her death."
     ],
     "explanation": "Only this option states what the poets have in common."
    },
    {
     "id": "sat.evidence#5",
     "prompt": "Which choice most logically completes the text? \"Crows that were shown a masked 'threatening' person scolded that mask for years afterward, and so did crows that never saw the original event. This suggests that crows ______\"",
     "answer": "can learn about threats from other crows.",
     "wrong": [
      "cannot recognize human faces.",
      "forget threats quickly.",
      "are only afraid of masks."
     ],
     "explanation": "Crows that never saw the event still reacted, implying social learning."
    }
   ]
  }
 ],
 "aiTopics": [
  {
   "subject": "satMath",
   "names": [
    "SAT Math: Hard Word Problems",
    "SAT Math: Nonlinear Functions",
    "SAT Math: Data Interpretation from Tables",
    "SAT Math: Scatterplots & Lines of Best Fit",
    "SAT Math: Two-Way Tables",
    "SAT Math: Equivalent Expressions",
    "SAT Math: Polynomial Division",
    "SAT Math: Rational Expressions",
    "SAT Math: Similar Triangles",
    "SAT Math: Arc Length & Sector Area",
    "SAT Math: Radians",
    "SAT Math: Complex Numbers",
    "SAT Math: Margin of Error & Sampling",
    "SAT Math: Hardest Desmos-Style Problems"
   ]
  },
  {
   "subject": "satReading",
   "names": [
    "SAT R&W: Cross-Text Connections",
    "SAT R&W: Text Structure & Purpose",
    "SAT R&W: Command of Evidence (Quantitative)",
    "SAT R&W: Inferences",
    "SAT R&W: Rhetorical Synthesis (Notes)",
    "SAT R&W: Poetry Passages",
    "SAT R&W: Science Passages",
    "SAT R&W: History Passages",
    "SAT R&W: Hard Vocabulary in Context",
    "SAT R&W: Supplements & Appositives",
    "SAT R&W: Parallel Structure"
   ]
  },
  {
   "subject": "math",
   "names": [
    "Pre-Algebra",
    "Algebra I",
    "Algebra II",
    "Geometry Proofs",
    "Trigonometric Identities",
    "Unit Circle",
    "Precalculus: Functions",
    "Conic Sections",
    "Limits",
    "Derivatives",
    "Chain Rule",
    "Related Rates",
    "Integrals",
    "Integration by Parts",
    "Series & Sequences",
    "Taylor Series",
    "Multivariable Calculus",
    "Linear Algebra: Matrices",
    "Eigenvalues & Eigenvectors",
    "Differential Equations",
    "Probability Theory",
    "Statistics: Hypothesis Testing",
    "Statistics: Confidence Intervals",
    "Discrete Math",
    "Number Theory",
    "Graph Theory",
    "Set Theory",
    "Logic & Proofs",
    "Vectors",
    "Complex Analysis Basics"
   ]
  },
  {
   "subject": "science",
   "names": [
    "AP Biology: Cell Biology",
    "AP Biology: Genetics",
    "AP Biology: Evolution",
    "AP Biology: Ecology",
    "AP Biology: Cellular Respiration",
    "Molecular Biology",
    "Microbiology",
    "Immunology",
    "Neuroscience",
    "Human Physiology",
    "Botany",
    "Zoology",
    "Marine Biology",
    "AP Chemistry: Stoichiometry",
    "AP Chemistry: Thermodynamics",
    "AP Chemistry: Equilibrium",
    "AP Chemistry: Acids & Bases",
    "Organic Chemistry: Functional Groups",
    "Organic Chemistry: Reactions",
    "Biochemistry",
    "AP Physics 1: Kinematics",
    "AP Physics 1: Forces",
    "AP Physics 1: Energy & Momentum",
    "AP Physics 2: Fluids",
    "AP Physics C: Electricity & Magnetism",
    "Waves & Optics",
    "Thermodynamics",
    "Quantum Mechanics Basics",
    "Special Relativity",
    "Nuclear Physics",
    "Astronomy & Astrophysics",
    "Earth Science: Plate Tectonics",
    "Meteorology",
    "Oceanography",
    "Environmental Science",
    "Climate Science",
    "Geology: Rocks & Minerals",
    "Paleontology",
    "Genetics & CRISPR",
    "Epidemiology"
   ]
  },
  {
   "subject": "history",
   "names": [
    "APUSH: Colonial America",
    "APUSH: American Revolution",
    "APUSH: Constitution & Early Republic",
    "APUSH: Jacksonian Era",
    "APUSH: Civil War & Reconstruction",
    "APUSH: Gilded Age",
    "APUSH: Progressive Era",
    "APUSH: 1920s & Great Depression",
    "APUSH: World War II",
    "APUSH: Cold War",
    "APUSH: Civil Rights Movement",
    "AP World: Classical Civilizations",
    "AP World: Silk Roads",
    "AP World: Mongol Empire",
    "AP World: Age of Exploration",
    "AP World: Industrial Revolution",
    "AP World: Imperialism",
    "AP World: Decolonization",
    "Ancient Egypt",
    "Ancient Greece",
    "Roman Republic & Empire",
    "Byzantine Empire",
    "Medieval Europe",
    "Renaissance",
    "Protestant Reformation",
    "French Revolution",
    "Napoleonic Era",
    "World War I",
    "Russian Revolution",
    "Holocaust",
    "Chinese Dynasties",
    "Japanese History",
    "Ottoman Empire",
    "History of India",
    "African Kingdoms",
    "Aztec, Maya & Inca",
    "Latin American Independence",
    "Space Race",
    "AP Gov: Constitution",
    "AP Gov: Supreme Court Cases",
    "AP Gov: Congress",
    "AP Gov: The Presidency",
    "Landmark Supreme Court Cases",
    "Comparative Government"
   ]
  },
  {
   "subject": "geography",
   "names": [
    "World Flags",
    "Rivers of the World",
    "Mountain Ranges",
    "Deserts",
    "Countries by Population",
    "European Geography",
    "Asian Geography",
    "African Geography",
    "South American Geography",
    "U.S. Geography",
    "Human Geography: Urbanization",
    "Human Geography: Migration",
    "Climate Zones",
    "Time Zones & Map Projections",
    "World Religions",
    "World Languages"
   ]
  },
  {
   "subject": "languages",
   "names": [
    "Spanish Grammar: Preterite vs Imperfect",
    "Spanish Subjunctive",
    "Spanish Travel Phrases",
    "French Grammar: Passé Composé",
    "French Subjunctive",
    "German Cases",
    "Italian Basics",
    "Portuguese Basics",
    "Japanese Hiragana",
    "Japanese Katakana",
    "Japanese N5 Vocabulary",
    "Mandarin HSK 1",
    "Mandarin HSK 2",
    "Korean Hangul",
    "Korean Basics",
    "Arabic Basics",
    "Russian Basics",
    "Latin Grammar",
    "ASL Basics",
    "English Grammar",
    "Commonly Confused Words",
    "Idioms & Expressions",
    "Etymology"
   ]
  },
  {
   "subject": "vocab",
   "names": [
    "GRE Vocabulary",
    "ACT English",
    "Advanced Vocabulary",
    "Words from Literature",
    "Business Vocabulary",
    "Medical Terminology",
    "Legal Terminology"
   ]
  },
  {
   "subject": "humanities",
   "names": [
    "AP English Literature",
    "AP English Language: Rhetoric",
    "Shakespeare",
    "Greek Tragedy",
    "Poetry & Poets",
    "American Literature",
    "British Literature",
    "World Literature",
    "Russian Literature",
    "Mythology: Norse",
    "Mythology: Egyptian",
    "Art History: Renaissance",
    "Art History: Impressionism",
    "Art History: Modern Art",
    "Architecture",
    "Classical Music",
    "Music Theory",
    "Jazz History",
    "Film History",
    "Philosophy: Ethics",
    "Philosophy: Epistemology",
    "Philosophy: Existentialism",
    "Logic & Fallacies",
    "Religious Studies",
    "Theater"
   ]
  },
  {
   "subject": "tech",
   "names": [
    "AP Computer Science A (Java)",
    "AP CS Principles",
    "Data Structures",
    "Algorithms",
    "Dynamic Programming",
    "Graph Algorithms",
    "Python Programming",
    "JavaScript",
    "Swift & iOS",
    "SQL & Databases",
    "Operating Systems",
    "Computer Networks",
    "Cybersecurity",
    "Cryptography",
    "Machine Learning",
    "Deep Learning",
    "Computer Architecture",
    "Git & Version Control",
    "Linux Command Line",
    "System Design",
    "Web Development",
    "Cloud Computing",
    "Theory of Computation"
   ]
  },
  {
   "subject": "social",
   "names": [
    "AP Psychology: Biological Bases",
    "AP Psychology: Cognition",
    "AP Psychology: Development",
    "AP Psychology: Disorders & Treatment",
    "Social Psychology",
    "Sociology",
    "Anthropology",
    "Cognitive Biases",
    "Research Methods",
    "Criminology",
    "Linguistics",
    "Education Theory"
   ]
  },
  {
   "subject": "business",
   "names": [
    "AP Microeconomics",
    "AP Macroeconomics",
    "Accounting Basics",
    "Corporate Finance",
    "Investing",
    "Stock Market",
    "Marketing",
    "Entrepreneurship",
    "Business Law",
    "Negotiation",
    "Game Theory",
    "Behavioral Economics",
    "International Trade",
    "Cryptocurrency & Blockchain",
    "Real Estate Basics",
    "Taxes 101"
   ]
  }
 ]
};
